### ISSUE TITLE
Multi User access

### ISSUE THREAD

**Issue by segsalerty2013** [dominhhai/express-authen#2]
### Use case
I am building a platform that has multiple user access. I.e user and admin and maybe more user entities with different login page. 

### Solution
Solving this by extending this middleware to handle this (v2.0.0 - a major release). also taking care of backward compatibility with the previous version so previous dependents wont break in update process.

@dominhhai

**Comment by dominhhai** [comment]
@segsalerty2013 Tks for your solution.
PR is welcome!

**Comment by segsalerty2013** [comment]
Hi @dominhhai . PR awaiting.
